<?php
session_start();
require('maincore.php');
require('./phptopdfapp/fpdf.php');

$checkStudent = dbquery("SELECT * FROM studenroll inner join student on enrol_stud_no=stud_no inner join section on enrol_section=section_name WHERE (enrol_section='".$_GET['classProfile']."' AND enrol_sy='".$_GET['enrol_sy']."' AND section_sy='".$_GET['enrol_sy']."'  AND (enrol_status1='ENROLLED' or enrol_status1='PROMOTED')) order by stud_gender desc, stud_lname asc, stud_fname asc");

class PDF extends FPDF{
	function Header()
	{
		global $current_school_region, $current_school_division, $current_school_district, $current_school_name, $current_school_code, $current_school_address;
		$this->Cell(115,4,"",0,0,'C');
		$this->Cell(30,4,"",0,0,'C');
		$this->SetFont('Courier','I',6);
		$this->Cell(170,-8,"DepEd Form 9",0,1,'L');
		$this->Ln(5);

		$this->Image('./assets/images/deped_word.png',155,10,15);
		$this->Image('./assets/images/sanhs_logo.png',261,10,10);
		
		$this->Cell(115,4,"",0,0,'C');
		$this->Cell(30,4,"",0,0,'C');
		$this->SetFont('Courier','',8);
		$this->Cell(115,4,"",0,0,'C');
		$this->Cell(30,4,"",0,0,'C');
		$this->Cell(115,2,"Republic of the Philippines",0,1,'C');
		$this->Cell(115,4,"",0,0,'C');
		$this->Cell(30,4,"",0,0,'C');
		$this->Cell(115,2,"Department of Education",0,1,'C');
		$this->Cell(115,4,"",0,0,'C');
		$this->Cell(30,4,"",0,0,'C');
		$this->Cell(115,2,$current_school_region,0,1,'C');
		$this->Cell(115,4,"",0,0,'C');
		$this->Cell(30,4,"",0,0,'C');
		$this->Cell(115,2,"Division of ".$current_school_division,0,1,'C');	
		
		$this->Cell(115,4,"",0,0,'C');
		$this->Cell(30,4,"",0,0,'C');
		$this->SetFont('Courier','B',8);
		$this->Cell(115,2,"District of ".$current_school_district,0,1,'C');
		$this->SetFont('Courier','B',9);
		$this->Cell(115,4,"",0,0,'C');
		$this->Cell(30,4,"",0,0,'C');
		$this->Cell(115,3,strtoupper($current_school_name),0,1,'C');	
		$this->SetFont('Courier','',8);
		$this->Cell(115,4,"",0,0,'C');
		$this->Cell(30,4,"",0,0,'C');
		$this->Cell(115,2,"School Code: ".$current_school_code,0,1,'C');	
		$this->SetFont('Courier','I',8);
		$this->Cell(115,4,"",0,0,'C');
		$this->Cell(30,4,"",0,0,'C');
		$this->Cell(115,3,$current_school_address,0,1,'C');	
	}
}

$pdf = new PDF('L','mm','Letter');

while($dataStudent = dbarray($checkStudent)){
	$pdf->AddPage();
	$pdf->Ln(5);
	$pdf->Cell(115,4,"",0,0,'C');
	$pdf->Cell(30,4,"",0,0,'C');
	$pdf->SetFont('Courier','',8);
	$pdf->Cell(20,3,"Name & LRN:",0,0,'L');
	$pdf->SetFont('Courier','B',8);	
	$pdf->Cell(25,3,mb_convert_encoding(strtoupper($dataStudent['stud_lname'].", ".$dataStudent['stud_fname']." ".($dataStudent['stud_xname']!=""?"":$dataStudent['stud_xname'])." ".($dataStudent['stud_mname']=="-"?"-":substr($dataStudent['stud_mname'],0,1)."."))." (".$dataStudent['stud_lrn'].")",'ISO-8859-1', 'UTF-8'),0,1,'L');
	$pdf->SetFont('Courier','',8);
	$pdf->Cell(115,4,"",0,0,'C');
	$pdf->Cell(30,4,"",0,0,'C');
	$pdf->Cell(8,3,"Age:",0,0,'L');
	$pdf->SetFont('Courier','B',8);	
	$date1 = strtotime(($_GET['enrol_sy']+1)."-03-31");
	$date2 = strtotime($dataStudent['stud_bdate']);
	$time_difference = $date1 - $date2;
	$seconds_per_year = 60*60*24*365;
	$years = (int) ($time_difference / $seconds_per_year);
	$pdf->Cell(8,3,$years,0,0,'L');
	$pdf->SetFont('Courier','',8);
	$pdf->Cell(8,3,"Sex:",0,0,'L');
	$pdf->SetFont('Courier','B',8);	
	$pdf->Cell(12,3,$dataStudent['stud_gender'],0,0,'L');
	$pdf->SetFont('Courier','',8);
	$pdf->SetFont('Courier','',8);
	$pdf->Cell(12,3,"Grade:",0,0,'L');
	$pdf->SetFont('Courier','B',8);	
	$pdf->Cell(8,3,$dataStudent['enrol_level'],0,0,'L');
	$pdf->SetFont('Courier','',8);
	$pdf->Cell(16,3,"Section:",0,0,'L');
	$pdf->SetFont('Courier','B',8);	
	$pdf->Cell(20,3,$dataStudent['enrol_section'],0,1,'L');
	$pdf->SetFont('Courier','',8);
	$pdf->Cell(115,4,"",0,0,'C');
	$pdf->Cell(30,4,"",0,0,'C');
	$pdf->Cell(22,3,"School Year:",0,0,'L');
	$pdf->SetFont('Courier','B',8);	
	$pdf->Cell(85,4,$current_sy."-".($current_sy+1),0,1,'L');
	$pdf->Ln(1);	
	$pdf->SetFont('Courier','',7);
	$pdf->Cell(115,4,"",0,0,'C');
	$pdf->Cell(30,4,"",0,0,'C');
	$pdf->Cell(115,2,"Dear Parent:",0,1,'L');
	$pdf->Cell(115,4,"",0,0,'C');
	$pdf->Cell(30,4,"",0,0,'C');
	$pdf->Cell(115,2,"  This report card shows the ability and progress your child has made in",0,1,'L');
	$pdf->Cell(115,4,"",0,0,'C');
	$pdf->Cell(30,4,"",0,0,'C');
	$pdf->Cell(115,2,"different learning areas as well as his/her core values.",0,1,'L');
	$pdf->Cell(115,4,"",0,0,'C');
	$pdf->Cell(30,4,"",0,0,'C');
	$pdf->Cell(115,2,"  The school welcomes you, should you desire to know more about your ",0,1,'L');
	$pdf->Cell(115,4,"",0,0,'C');
	$pdf->Cell(30,4,"",0,0,'C');
	$pdf->Cell(115,2,"child's progress.",0,1,'L');
	$pdf->Ln(5);
	$pdf->SetFont('Courier','',10);
	$pdf->Cell(115,4,"",0,0,'C');
	$pdf->Cell(30,4,"",0,0,'C');
	$pdf->SetFont('Courier','BU',10);
	$pdf->Cell(50,4,"",0,0,'C');
	$pdf->Cell(65,4,mb_convert_encoding(strtoupper($dataStudent['user_fullname']),'ISO-8859-1', 'UTF-8'),0,1,'C');
	$pdf->SetFont('Courier','',8);
	$pdf->Cell(115,4,"",0,0,'C');
	$pdf->Cell(30,4,"",0,0,'C');
	$pdf->Cell(50,4,"",0,0,'C');
	$pdf->Cell(65,4,"Adviser",0,1,'C');
	$pdf->SetFont('Courier','',10);
	$pdf->Cell(115,4,"",0,0,'C');
	$pdf->Cell(30,4,"",0,0,'C');
	$pdf->SetFont('Courier','BU',10);
	$pdf->Cell(115,4,mb_convert_encoding(strtoupper($current_principal),'ISO-8859-1', 'UTF-8'),0,1,'L');
	$pdf->SetFont('Courier','',10);
	$pdf->Cell(115,4,"",0,0,'C');
	$pdf->Cell(30,4,"",0,0,'C');
	$pdf->SetFont('Courier','',8);
	$pdf->Cell(115,4,"School Head/In-Charge",0,1,'L');
	$pdf->Ln(10);
	$pdf->SetFont('Courier','',10);
	$pdf->Cell(115,4,"",0,0,'C');
	$pdf->Cell(30,4,"",0,0,'C');
	$pdf->SetFont('Courier','B',10);
	$pdf->Cell(115,4,"Certificate of Transfer",0,1,'C');
	$pdf->Ln(1);
	$pdf->SetFont('Courier','',10);
	$pdf->Cell(115,4,"",0,0,'C');
	$pdf->Cell(30,4,"",0,0,'C');
	$pdf->Cell(41,4,"Admitted to Grade:",0,0,'L');
	$pdf->Cell(15,4,"",'B',0,'L');
	$pdf->Cell(24,4,"  Section:",0,0,'L');
	$pdf->Cell(35,4,"",'B',1,'L');
	$pdf->Cell(115,4,"",0,0,'C');
	$pdf->Cell(30,4,"",0,0,'C');
	$pdf->Cell(78,4,"Eligibility for Admission to Grade:",0,0,'L');
	$pdf->Cell(37,4,"",'B',1,'L');
	$pdf->Ln(2);
	$pdf->Cell(115,4,"",0,0,'C');
	$pdf->Cell(30,4,"",0,0,'C');
	$pdf->Cell(115,4,"Approved: ",0,1,'L');
	$pdf->Ln(5);
	$pdf->Cell(115,4,"",0,0,'C');
	$pdf->Cell(30,4,"",0,0,'C');
	$pdf->SetFont('Courier','BU',10);
	$pdf->Cell(55,4,mb_convert_encoding(strtoupper($current_principal),'ISO-8859-1', 'UTF-8'),0,0,'C');
	$pdf->Cell(5,4,"",0,0,'L');
	$pdf->Cell(55,4,mb_convert_encoding(strtoupper($dataStudent['user_fullname']),'ISO-8859-1', 'UTF-8'),0,1,'C');
	$pdf->Cell(115,4,"",0,0,'C');
	$pdf->Cell(30,4,"",0,0,'C');
	$pdf->SetFont('Courier','',8);
	$pdf->Cell(55,4,"School Head/In-Charge",0,0,'C');
	$pdf->Cell(5,4,"",0,0,'L');
	$pdf->Cell(55,4,"Adviser",0,1,'C');
	$pdf->Ln(8);
	$pdf->SetFont('Courier','',10);
	$pdf->Cell(115,4,"",0,0,'C');
	$pdf->Cell(30,4,"",0,0,'C');
	$pdf->SetFont('Courier','b',10);
	$pdf->Cell(115,4,"Cancellation of Elligibility to Transfer",0,1,'C');
	$pdf->Ln(1);
	$pdf->SetFont('Courier','',10);
	$pdf->Cell(115,4,"",0,0,'C');
	$pdf->Cell(30,4,"",0,0,'C');
	$pdf->Cell(115,4,"Admitted in: _________________________________________",0,1,'L');
	$pdf->Cell(115,4,"",0,0,'C');
	$pdf->Cell(30,4,"",0,0,'C');
	$pdf->Cell(115,4,"Date:____________",0,1,'L');
	$pdf->Ln(2);
	$pdf->Cell(115,4,"",0,0,'C');
	$pdf->Cell(30,4,"",0,0,'C');
	$pdf->Cell(50,4,"",0,0,'L');
	$pdf->Cell(65,4,"_______________________",0,1,'C');
	$pdf->Cell(115,4,"",0,0,'C');
	$pdf->Cell(30,4,"",0,0,'C');
	$pdf->Cell(50,4,"",0,0,'L');
	$pdf->SetFont('Courier','',8);
	$pdf->Cell(65,4,"School Head/In-Charge",0,1,'C');
}
$pdf->Output();
?>
