<?php
session_start();
require('maincore.php');
require('./phptopdfapp/fpdf.php');

$checkStudent = dbquery("select * from student inner join studcontacts on stud_no=studCont_stud_no inner join studenroll on stud_no=enrol_stud_no inner join section on enrol_section=section_name inner join users on section_adviser=user_no where (stud_no='".$_GET['stud_no']."' and enrol_sy='".$_GET['enrol_sy']."') order by studCont_no asc");
$dataStudent = dbarray($checkStudent);

class PDF extends FPDF{
	function Header()
	{
	}
}

$pdf = new PDF('L','mm','Letter');
$pdf->AddPage();

$pdf->SetFont('Courier','I',6);
$pdf->Cell(115,4,"",0,0,'C');
$pdf->Cell(30,4,"",0,0,'C');
$pdf->Cell(170,-8,"DepEd Form 138",0,1,'L');
$pdf->Ln(10);
$pdf->SetFont('Courier','',9);
$pdf->Image('./assets/images/deped_word.png',160,15,20);
$pdf->Cell(115,4,"",0,0,'C');
$pdf->Cell(30,4,"",0,0,'C');
$pdf->Image('./assets/images/sanhs_logo.png',250,15,15);
$student_image = "./assets/images/students/".$_GET['stud_no'].".jpg";
$no_image = "./assets/images/noimage.jpg";
$pdf->Image(file_exists($student_image) ? $student_image : $no_image,240,45,30);
$pdf->Cell(115,4,"Republic of the Philippines",0,1,'C');
$pdf->Cell(115,4,"",0,0,'C');
$pdf->Cell(30,4,"",0,0,'C');
$pdf->SetFont('Courier','',9);
$pdf->Cell(115,4,"Department of Education",0,1,'C');
$pdf->SetFont('Courier','',9);
$pdf->Cell(115,4,"",0,0,'C');
$pdf->Cell(30,4,"",0,0,'C');
$pdf->Cell(115,4,$current_school_region,0,1,'C');
$pdf->Cell(115,4,"",0,0,'C');
$pdf->Cell(30,4,"",0,0,'C');
$pdf->Cell(115,4,"Division of ".$current_school_division,0,1,'C');	
$pdf->Cell(115,4,"",0,0,'C');
$pdf->Cell(30,4,"",0,0,'C');
$pdf->SetFont('Courier','B',9);
$pdf->Cell(115,4,"District of ".$current_school_district,0,1,'C');	
$pdf->Cell(115,4,"",0,0,'C');
$pdf->Cell(30,4,"",0,0,'C');
$pdf->SetFont('Courier','B',10);
$pdf->Cell(115,4,strtoupper($current_school_name),0,1,'C');	
$pdf->Cell(115,4,"",0,0,'C');
$pdf->Cell(30,4,"",0,0,'C');
$pdf->SetFont('Courier','',9);
$pdf->Cell(115,4,"School Code: ".$current_school_code,0,1,'C');	
$pdf->Cell(115,4,"",0,0,'C');
$pdf->Cell(30,4,"",0,0,'C');
$pdf->SetFont('Courier','I',9);
$pdf->Cell(115,4,$current_school_address,0,1,'C');	

$pdf->Ln(8);
$pdf->Cell(115,4,"",0,0,'C');
$pdf->Cell(30,4,"",0,0,'C');
$pdf->SetFont('Courier','',10);
$pdf->Cell(10,4,"LRN:",0,0,'L');
$pdf->SetFont('Courier','BU',10);	
$pdf->Cell(40,4,$dataStudent['stud_lrn'],0,1,'L');
$pdf->SetFont('Courier','',10);
$pdf->Cell(115,4,"",0,0,'C');
$pdf->Cell(30,4,"",0,0,'C');
$pdf->Cell(12,4,"Name:",0,0,'L');
$pdf->SetFont('Courier','BU',10);	
$pdf->Cell(100,4,mb_convert_encoding(strtoupper($dataStudent['stud_lname'].", ".$dataStudent['stud_fname']." ".($dataStudent['stud_xname']!=""?"":$dataStudent['stud_xname'])." ".($dataStudent['stud_mname']=="-"?"-":substr($dataStudent['stud_mname'],0,1).".")),'ISO-8859-1', 'UTF-8'),0,1,'L');
$pdf->SetFont('Courier','',10);
$pdf->Cell(115,4,"",0,0,'C');
$pdf->Cell(30,4,"",0,0,'C');
$pdf->Cell(10,4,"Age:",0,0,'L');
$pdf->SetFont('Courier','BU',10);	

$date1 = strtotime(($_GET['enrol_sy']+1)."-03-31");
$date2 = strtotime($dataStudent['stud_bdate']);
$time_difference = $date1 - $date2;
$seconds_per_year = 60*60*24*365;
$years = (int) ($time_difference / $seconds_per_year);
$pdf->Cell(10,4,$years,0,0,'L');
$pdf->SetFont('Courier','',10);
$pdf->Cell(10,4,"Sex:",0,0,'L');
$pdf->SetFont('Courier','BU',10);	
$pdf->Cell(20,4,$dataStudent['stud_gender'],0,1,'L');
$pdf->SetFont('Courier','',10);
$pdf->Cell(115,4,"",0,0,'C');
$pdf->Cell(30,4,"",0,0,'C');
$pdf->SetFont('Courier','',10);
$pdf->Cell(14,4,"Grade:",0,0,'L');
$pdf->SetFont('Courier','BU',10);	
$pdf->Cell(10,4,$dataStudent['enrol_level'],0,0,'L');
$pdf->SetFont('Courier','',10);
$pdf->Cell(18,4,"Section:",0,0,'L');
$pdf->SetFont('Courier','BU',10);	
$pdf->Cell(20,4,$dataStudent['enrol_section'],0,1,'L');
$pdf->SetFont('Courier','',10);
$pdf->Cell(115,4,"",0,0,'C');
$pdf->Cell(30,4,"",0,0,'C');
$pdf->Cell(28,4,"School Year:",0,0,'L');
$pdf->SetFont('Courier','BU',10);	
$pdf->Cell(85,4,$current_sy."-".($current_sy+1),0,1,'L');
$pdf->Ln(5);	
$pdf->SetFont('Courier','',9);
$pdf->Cell(115,4,"",0,0,'C');
$pdf->Cell(30,4,"",0,0,'C');
$pdf->Cell(115,4,"Dear Parent:",0,1,'L');
$pdf->Cell(115,4,"",0,0,'C');
$pdf->Cell(30,4,"",0,0,'C');
$pdf->Cell(115,4,"  This report card shows the ability and progress your",0,1,'L');
$pdf->Cell(115,4,"",0,0,'C');
$pdf->Cell(30,4,"",0,0,'C');
$pdf->Cell(115,4,"child has made in different learning areas as well as his/",0,1,'L');
$pdf->Cell(115,4,"",0,0,'C');
$pdf->Cell(30,4,"",0,0,'C');
$pdf->Cell(115,4,"her core values.",0,1,'L');
$pdf->Cell(115,4,"",0,0,'C');
$pdf->Cell(30,4,"",0,0,'C');
$pdf->Cell(115,4,"  The school welcomes you, should you desire to know more",0,1,'L');
$pdf->Cell(115,4,"",0,0,'C');
$pdf->Cell(30,4,"",0,0,'C');
$pdf->Cell(115,4,"about your child's progress.",0,1,'L');
$pdf->Ln(5);
$pdf->SetFont('Courier','',10);
$pdf->Cell(115,4,"",0,0,'C');
$pdf->Cell(30,4,"",0,0,'C');
$pdf->SetFont('Courier','BU',10);
$pdf->Cell(50,4,"",0,0,'C');
$pdf->Cell(65,4,mb_convert_encoding(strtoupper($dataStudent['user_fullname']),'ISO-8859-1', 'UTF-8'),0,1,'C');
$pdf->SetFont('Courier','',8);
$pdf->Cell(115,4,"",0,0,'C');
$pdf->Cell(30,4,"",0,0,'C');
$pdf->Cell(50,4,"",0,0,'C');
$pdf->Cell(65,4,"Adviser",0,1,'C');
$pdf->SetFont('Courier','',10);
$pdf->Cell(115,4,"",0,0,'C');
$pdf->Cell(30,4,"",0,0,'C');
$pdf->SetFont('Courier','BU',10);
$pdf->Cell(115,4,mb_convert_encoding(strtoupper($current_principal),'ISO-8859-1', 'UTF-8'),0,1,'L');
$pdf->SetFont('Courier','',10);
$pdf->Cell(115,4,"",0,0,'C');
$pdf->Cell(30,4,"",0,0,'C');
$pdf->SetFont('Courier','',8);
$pdf->Cell(115,4,"School Head/In-Charge",0,1,'L');
$pdf->Ln(10);
$pdf->SetFont('Courier','',10);
$pdf->Cell(115,4,"",0,0,'C');
$pdf->Cell(30,4,"",0,0,'C');
$pdf->SetFont('Courier','B',10);
$pdf->Cell(115,4,"Certificate of Transfer",0,1,'C');
$pdf->Ln(1);
$pdf->SetFont('Courier','',10);
$pdf->Cell(115,4,"",0,0,'C');
$pdf->Cell(30,4,"",0,0,'C');
$pdf->Cell(41,4,"Admitted to Grade:",0,0,'L');
$pdf->Cell(15,4,"",'B',0,'L');
$pdf->Cell(24,4,"  Section:",0,0,'L');
$pdf->Cell(35,4,"",'B',1,'L');
$pdf->Cell(115,4,"",0,0,'C');
$pdf->Cell(30,4,"",0,0,'C');
$pdf->Cell(78,4,"Eligibility for Admission to Grade:",0,0,'L');
$pdf->Cell(37,4,"",'B',1,'L');
$pdf->Ln(2);
$pdf->Cell(115,4,"",0,0,'C');
$pdf->Cell(30,4,"",0,0,'C');
$pdf->Cell(115,4,"Approved: ",0,1,'L');
$pdf->Ln(5);
$pdf->Cell(115,4,"",0,0,'C');
$pdf->Cell(30,4,"",0,0,'C');
$pdf->SetFont('Courier','BU',10);
$pdf->Cell(55,4,mb_convert_encoding(strtoupper($current_principal),'ISO-8859-1', 'UTF-8'),0,0,'C');
$pdf->Cell(5,4,"",0,0,'L');
$pdf->Cell(55,4,mb_convert_encoding(strtoupper($dataStudent['user_fullname']),'ISO-8859-1', 'UTF-8'),0,1,'C');
$pdf->Cell(115,4,"",0,0,'C');
$pdf->Cell(30,4,"",0,0,'C');
$pdf->SetFont('Courier','',8);
$pdf->Cell(55,4,"School Head/In-Charge",0,0,'C');
$pdf->Cell(5,4,"",0,0,'L');
$pdf->Cell(55,4,"Adviser",0,1,'C');
$pdf->Ln(8);
$pdf->SetFont('Courier','',10);
$pdf->Cell(115,4,"",0,0,'C');
$pdf->Cell(30,4,"",0,0,'C');
$pdf->SetFont('Courier','b',10);
$pdf->Cell(115,4,"Cancellation of Elligibility to Transfer",0,1,'C');
$pdf->Ln(1);
$pdf->SetFont('Courier','',10);
$pdf->Cell(115,4,"",0,0,'C');
$pdf->Cell(30,4,"",0,0,'C');
$pdf->Cell(115,4,"Admitted in: _________________________________________",0,1,'L');
$pdf->Cell(115,4,"",0,0,'C');
$pdf->Cell(30,4,"",0,0,'C');
$pdf->Cell(115,4,"Date:____________",0,1,'L');
$pdf->Ln(2);
$pdf->Cell(115,4,"",0,0,'C');
$pdf->Cell(30,4,"",0,0,'C');
$pdf->Cell(50,4,"",0,0,'L');
$pdf->Cell(65,4,"_______________________",0,1,'C');
$pdf->Cell(115,4,"",0,0,'C');
$pdf->Cell(30,4,"",0,0,'C');
$pdf->Cell(50,4,"",0,0,'L');
$pdf->SetFont('Courier','',8);
$pdf->Cell(65,4,"School Head/In-Charge",0,1,'C');

$pdf->SetY(10);
$pdf->SetFont('Courier','B',12);
$pdf->Cell(115,15,"REPORT ON ATTENDANCE",0,1,'C');
$pdf->SetFont('Courier','B',8);
$pdf->Cell(23,8,"",1,0,'C');
$pdf->Cell(7,8,"Jun",1,0,'C');
$pdf->Cell(7,8,"Jul",1,0,'C');
$pdf->Cell(7,8,"Aug",1,0,'C');
$pdf->Cell(7,8,"Sep",1,0,'C');
$pdf->Cell(7,8,"Oct",1,0,'C');
$pdf->Cell(7,8,"Nov",1,0,'C');
$pdf->Cell(7,8,"Dec",1,0,'C');
$pdf->Cell(7,8,"Jan",1,0,'C');
$pdf->Cell(7,8,"Feb",1,0,'C');
$pdf->Cell(7,8,"Mar",1,0,'C');
$pdf->Cell(7,8,"Apr",1,0,'C');
$pdf->Cell(15,8,"Total",1,1,'C');

$checkSchoolDays = dbquery("SELECT * FROM school_days WHERE (sch_sy='".$_GET['enrol_sy']."' AND sch_stud_no='".$_GET['enrol_sy']."')");
$dataSchoolsDays = dbarray($checkSchoolDays);
$pdf->SetFont('Courier','',7);
$pdf->Cell(23,10,"School Days",'LBR',0,'C');
$pdf->SetFont('Courier','B',9);
$pdf->Cell(7,10,$dataSchoolsDays['sch_m1'],'LBR',0,'C');
$pdf->Cell(7,10,$dataSchoolsDays['sch_m2'],'LBR',0,'C');
$pdf->Cell(7,10,$dataSchoolsDays['sch_m3'],'LBR',0,'C');
$pdf->Cell(7,10,$dataSchoolsDays['sch_m4'],'LBR',0,'C');
$pdf->Cell(7,10,$dataSchoolsDays['sch_m5'],'LBR',0,'C');
$pdf->Cell(7,10,$dataSchoolsDays['sch_m6'],'LBR',0,'C');
$pdf->Cell(7,10,$dataSchoolsDays['sch_m7'],'LBR',0,'C');
$pdf->Cell(7,10,$dataSchoolsDays['sch_m8'],'LBR',0,'C');
$pdf->Cell(7,10,$dataSchoolsDays['sch_m9'],'LBR',0,'C');
$pdf->Cell(7,10,$dataSchoolsDays['sch_m10'],'LBR',0,'C');
$pdf->Cell(7,10,$dataSchoolsDays['sch_m11'],'LBR',0,'C');
$totalSchoolDays = $dataSchoolsDays['sch_m1'] + $dataSchoolsDays['sch_m2'] + $dataSchoolsDays['sch_m3'] + $dataSchoolsDays['sch_m4'] + $dataSchoolsDays['sch_m5'] +$dataSchoolsDays['sch_m6'] + $dataSchoolsDays['sch_m7'] + $dataSchoolsDays['sch_m8'] + $dataSchoolsDays['sch_m9'] + $dataSchoolsDays['sch_m10'] + $dataSchoolsDays['sch_m11'] + $dataSchoolsDays['sch_m12'];
$pdf->Cell(15,10,$totalSchoolDays,'LBR',1,'C');


$checkPresentDays = dbquery("SELECT * FROM school_days WHERE (sch_sy='".$_GET['enrol_sy']."' AND sch_stud_no='".$_GET['stud_no']."')");
$dataPresentDays = dbarray($checkPresentDays);
$pdf->SetFont('Courier','',7);
$pdf->Cell(23,10,"Days Present",'LBR',0,'C');
$pdf->SetFont('Courier','B',9);
$pdf->Cell(7,10,($dataPresentDays['sch_m1']==0?"":$dataPresentDays['sch_m1']),'LBR',0,'C');
$pdf->Cell(7,10,($dataPresentDays['sch_m2']==0?"":$dataPresentDays['sch_m2']),'LBR',0,'C');
$pdf->Cell(7,10,($dataPresentDays['sch_m3']==0?"":$dataPresentDays['sch_m3']),'LBR',0,'C');
$pdf->Cell(7,10,($dataPresentDays['sch_m4']==0?"":$dataPresentDays['sch_m4']),'LBR',0,'C');
$pdf->Cell(7,10,($dataPresentDays['sch_m5']==0?"":$dataPresentDays['sch_m5']),'LBR',0,'C');
$pdf->Cell(7,10,($dataPresentDays['sch_m6']==0?"":$dataPresentDays['sch_m6']),'LBR',0,'C');
$pdf->Cell(7,10,($dataPresentDays['sch_m7']==0?"":$dataPresentDays['sch_m7']),'LBR',0,'C');
$pdf->Cell(7,10,($dataPresentDays['sch_m8']==0?"":$dataPresentDays['sch_m8']),'LBR',0,'C');
$pdf->Cell(7,10,($dataPresentDays['sch_m9']==0?"":$dataPresentDays['sch_m9']),'LBR',0,'C');
$pdf->Cell(7,10,($dataPresentDays['sch_m10']==0?"":$dataPresentDays['sch_m10']),'LBR',0,'C');
$pdf->Cell(7,10,($dataPresentDays['sch_m11']==0?"":$dataPresentDays['sch_m11']),'LBR',0,'C');
$totalPresentDays = $dataPresentDays['sch_m1'] + $dataPresentDays['sch_m2'] + $dataPresentDays['sch_m3'] + $dataPresentDays['sch_m4'] + $dataPresentDays['sch_m5'] +$dataPresentDays['sch_m6'] + $dataPresentDays['sch_m7'] + $dataPresentDays['sch_m8'] + $dataPresentDays['sch_m9'] + $dataPresentDays['sch_m10'] + $dataPresentDays['sch_m11'] + $dataPresentDays['sch_m12'];
$pdf->Cell(15,10,($dataPresentDays['sch_m1']==0 || $dataPresentDays['sch_m2']==0 || $dataPresentDays['sch_m3']==0 || $dataPresentDays['sch_m4']==0 || $dataPresentDays['sch_m5']==0 || $dataPresentDays['sch_m6']==0 || $dataPresentDays['sch_m7']==0 || $dataPresentDays['sch_m8']==0 || $dataPresentDays['sch_m9']==0 || $dataPresentDays['sch_m10']==0 || $dataPresentDays['sch_m11']==0?"":$totalPresentDays),'LBR',1,'C');

$AbsentDays_sch_m1 = $dataSchoolsDays['sch_m1']- $dataPresentDays['sch_m1'];
$AbsentDays_sch_m2 = $dataSchoolsDays['sch_m2']- $dataPresentDays['sch_m2'];
$AbsentDays_sch_m3 = $dataSchoolsDays['sch_m3']- $dataPresentDays['sch_m3'];
$AbsentDays_sch_m4 = $dataSchoolsDays['sch_m4']- $dataPresentDays['sch_m4'];
$AbsentDays_sch_m5 = $dataSchoolsDays['sch_m5']- $dataPresentDays['sch_m5'];
$AbsentDays_sch_m6 = $dataSchoolsDays['sch_m6']- $dataPresentDays['sch_m6'];
$AbsentDays_sch_m7 = $dataSchoolsDays['sch_m7']- $dataPresentDays['sch_m7'];
$AbsentDays_sch_m8 = $dataSchoolsDays['sch_m8']- $dataPresentDays['sch_m8'];
$AbsentDays_sch_m9 = $dataSchoolsDays['sch_m9']- $dataPresentDays['sch_m9'];
$AbsentDays_sch_m10 = $dataSchoolsDays['sch_m10']- $dataPresentDays['sch_m10'];
$AbsentDays_sch_m11 = $dataSchoolsDays['sch_m11']- $dataPresentDays['sch_m11'];
$AbsentDays_sch_m12 = $dataSchoolsDays['sch_m12']- $dataPresentDays['sch_m12'];
$totalAbsentDays = $AbsentDays_sch_m1 + $AbsentDays_sch_m2 + $AbsentDays_sch_m3 + $AbsentDays_sch_m4 + $AbsentDays_sch_m5 + $AbsentDays_sch_m6 + $AbsentDays_sch_m7 + $AbsentDays_sch_m8 + $AbsentDays_sch_m9 + $AbsentDays_sch_m10 + $AbsentDays_sch_m11 + $AbsentDays_sch_m12;

$pdf->SetFont('Courier','',7);
$pdf->Cell(23,10,"Days Absent",'LBR',0,'C');
$pdf->SetFont('Courier','B',9);
$pdf->Cell(7,10,($dataPresentDays['sch_m1']==0?"":$AbsentDays_sch_m1),'LBR',0,'C');
$pdf->Cell(7,10,($dataPresentDays['sch_m2']==0?"":$AbsentDays_sch_m2),'LBR',0,'C');
$pdf->Cell(7,10,($dataPresentDays['sch_m3']==0?"":$AbsentDays_sch_m3),'LBR',0,'C');
$pdf->Cell(7,10,($dataPresentDays['sch_m4']==0?"":$AbsentDays_sch_m4),'LBR',0,'C');
$pdf->Cell(7,10,($dataPresentDays['sch_m5']==0?"":$AbsentDays_sch_m5),'LBR',0,'C');
$pdf->Cell(7,10,($dataPresentDays['sch_m6']==0?"":$AbsentDays_sch_m6),'LBR',0,'C');
$pdf->Cell(7,10,($dataPresentDays['sch_m7']==0?"":$AbsentDays_sch_m7),'LBR',0,'C');
$pdf->Cell(7,10,($dataPresentDays['sch_m8']==0?"":$AbsentDays_sch_m8),'LBR',0,'C');
$pdf->Cell(7,10,($dataPresentDays['sch_m9']==0?"":$AbsentDays_sch_m9),'LBR',0,'C');
$pdf->Cell(7,10,($dataPresentDays['sch_m10']==0?"":$AbsentDays_sch_m10),'LBR',0,'C');
$pdf->Cell(7,10,($dataPresentDays['sch_m11']==0?"":$AbsentDays_sch_m11),'LBR',0,'C');
$pdf->Cell(15,10,($dataPresentDays['sch_m1']==0 || $dataPresentDays['sch_m2']==0 || $dataPresentDays['sch_m3']==0 || $dataPresentDays['sch_m4']==0 || $dataPresentDays['sch_m5']==0 || $dataPresentDays['sch_m6']==0 || $dataPresentDays['sch_m7']==0 || $dataPresentDays['sch_m8']==0 || $dataPresentDays['sch_m9']==0 || $dataPresentDays['sch_m10']==0 || $dataPresentDays['sch_m11']==0?"":$totalAbsentDays),'LBR',1,'C');


$pdf->Ln(20);
$pdf->SetFont('Courier','B',12);
$pdf->Cell(115,15,"PARENT/GUARDIAN'S SIGNATURE",0,1,'C');
$pdf->SetFont('Courier','',10);
$pdf->Cell(115,8,"1st Quarter		_____________________________",0,1,'C');
$pdf->Cell(115,8,"2nd Quarter		_____________________________",0,1,'C');
$pdf->Cell(115,8,"3rd Quarter		_____________________________",0,1,'C');
$pdf->Cell(115,8,"4th Quarter		_____________________________",0,1,'C');

$pdf->AddPage();
$pdf->Ln(5);
$pdf->Cell(115,4,"",0,0,'C');
$pdf->Cell(30,4,"",0,0,'C');
$pdf->SetFont('Courier','B',12);
$pdf->Cell(115,4,"REPORT ON LEARNER'S OBSERVED VALUES",0,1,'C');
$pdf->Ln(5);
$pdf->Cell(115,4,"",0,0,'C');
$pdf->Cell(30,4,"",0,0,'C');
$pdf->SetFont('Courier','B',9);
$pdf->Cell(32,8,"Core Values",1,0,'C');
$pdf->Cell(51,8,"Behavior Statements",1,0,'C');
$pdf->Cell(32,4,"Quarter",1,2,'C');
$pdf->Cell(8,4,"1",1,0,'C');
$pdf->Cell(8,4,"2",1,0,'C');
$pdf->Cell(8,4,"3",1,0,'C');
$pdf->Cell(8,4,"4",1,1,'C');
$pdf->Cell(115,4,"",0,0,'C');
$pdf->Cell(30,4,"",0,0,'C');
$pdf->SetFont('Courier','',9);
$pdf->Cell(32,28,"1.Maka-Diyos",1,0,'L');
$pdf->MultiCell(51,4,"Expresses one's spiritual beliefs while respecting the spiritual beliefs of others",1,'L');
$pdf->Ln(-20);
$pdf->Cell(228,20,"",0,0,'C');
$pdf->Cell(8,16,"",1,0,'C');
$pdf->Cell(8,16,"",1,0,'C');
$pdf->Cell(8,16,"",1,0,'C');
$pdf->Cell(8,16,"",1,1,'C');


$pdf->Cell(115,4,"",0,0,'C');
$pdf->Cell(30,4,"",0,0,'C');
$pdf->Cell(32,4,"",0,0,'C');
$pdf->SetFont('Courier','',9);
$pdf->MultiCell(51,4,"Shows adherence to ethical principles by upholding truth",1,'L');
$pdf->Cell(115,4,"",0,0,'C');
$pdf->Cell(30,4,"",0,0,'C');
$pdf->Cell(32,24,"2.Maka-tao",1,0,'L');
$pdf->MultiCell(51,4,"Is sensitive to individual, social, and cultural differences",1,'L');
$pdf->Cell(115,4,"",0,0,'C');
$pdf->Cell(30,4,"",0,0,'C');
$pdf->Cell(32,4,"",0,0,'C');
$pdf->SetFont('Courier','',9);
$pdf->MultiCell(51,4,"Demonstrates contributions toward solidarity",1,'L');
$pdf->Cell(115,4,"",0,0,'C');
$pdf->Cell(30,4,"",0,0,'C');
$pdf->Cell(32,20,"3.Maka-kalikasan",1,0,'L');
$pdf->MultiCell(51,4,"Cares for the environement and utilizes resources wisely, judiciously, and economically",1,'L');
$pdf->Cell(115,4,"",0,0,'C');
$pdf->Cell(30,4,"",0,0,'C');
$pdf->SetFont('Courier','',9);
$pdf->Cell(32,36,"4.Maka-bansa",1,0,'L');
$pdf->MultiCell(51,4,"Demonstrate pride in being a Filipino; exercises the rights and responsibilities of a Filipino citizen",1,'L');
$pdf->Cell(115,4,"",0,0,'C');
$pdf->Cell(30,4,"",0,0,'C');
$pdf->Cell(32,4,"",0,0,'C');
$pdf->SetFont('Courier','',9);
$pdf->MultiCell(51,4,"Demonstrates appropriate behavior in carrying out activities in the school, community, and country",1,'L');
$pdf->Output();
?>
